### ISSUE TITLE
Improved invocation of generic smart functions with parameters

### ISSUE THREAD

**Issue by xpertservice** [fluree/db#12]
It would be desirable that generic collection / predicate "_fn" "spec"s with parameters ("params") can be invoked without the need to create additional  application specific "_fn" smart functions. 
**Example schema to define a "range check" and "required predicates"**
**Application_fnlib:**
[{
    "_id": "_fn$range?",
    "name": "range?",
    "doc": "Checks if in range [min,max]",
    "params": ["min","max"],
    "code": "(and (>= (?o) min ) (<= (?o) max))"
},
{
    "_id": "_fn$range?5-10",
    "name": "range?5-10",
    "doc": "Checks that the domain is between 5 and 10",
    "code": "(range? 5 10)"
},
{
    "_id": "_fn$required",
    "name": "required",
    "params": ["predicateName"],
    "doc": "Checks that the collection has a certain predicate",
    "code": "(boolean (get (?s) predicateName))"
},
{
    "_id": "_fn$person_requirements",
    "name": "person_requirements",
    "doc": "Checks that the collection person has certain predicates",
    "code": "(and (required \"person/firstName\") (required \"person/lastName\"))"
}]
**Application DB schema:**
[{
    "_id": "_collection",
    "name": "person",
    "spec": [["_fn/name", "person_required_firstName"], ["_fn/name", "person_required_lastName"]],
    "specDoc": "A Person requires a firstName and a lastName"
},
{
    "_id": "_predicate",
    "name": "person/type",
    "type": "int",
    "spec": [["_fn/name", "range?5-10"]],
    "specDoc": "person/type out-of-range [5,10]"
}]

**This could  be expressed like :**

**Application_fnlib:**
[{
    "_id": "_fn$range?",
    "name": "range?",
    "doc": "Checks if in range [min,max]",
    "params": ["min","max"],
    "code": "(and (>= (?o) min ) (<= (?o) max))"
},
{
    "_id": "_fn$required",
    "name": "required",
    "params": ["predicateName"],
    "doc": "Checks that the collection has a certain predicate",
    "code": "(boolean (get (?s) predicateName))"
}]

**Application DB schema:**
[{
    "_id": "_collection",
    "name": "person",
    "spec": [["_fn/name", "required", {\"person/firstName\", \"person/lastName\"}]],
    "specDoc": "A Person requires a firstName and a lastName"
},
{
    "_id": "_predicate",
    "name": "person/type",
    "type": "int",
    "spec": [["_fn/name", "range?", 5, 10]],
    "specDoc": "person/type out of range [5,10]"
}]

**Comment by ldw1007** [comment]
FYI - we are tracking this improvement under FC-909.  Although not scheduled for a short-term deliverable, the feature is under discussion as to how it should be implemented.

**Comment by bplatz** [comment]
@xpertservice Just an update here - this will be coming and is targeted to get included in the 1.0 final release as of right now - we are still working through some decisions, but are actively working the issue.

**Comment by bplatz** [comment]
With SmartFunctions now replaced with PolicyQueries, query statements and express far more logic than these functions ever supported. This issue is therefore no longer relevant to v3
