### ISSUE TITLE
Simple sparql query

### ISSUE THREAD

**Issue by luisenriqueramos1977** [fluree/db#192]
I am trying to do a simple sparql query:
SELECT *
WHERE {
    ?s ?p ?o .
}

which should show me all database data, however it throws an error, which should be the appropriate notation?

Luis Ramos

**Comment by bplatz** [comment]
Today we force you to specify at least a collection, a fully database dump is not allowed. 

This is more a function of of an initial direction that most ledgers would be policy-driven (SmartFunction controlled) and interaction would be driven by apps.

With more people using Fluree as a knowledge graph however, it makes sense for us to allow this (fuel-permitting) and we'll look to no longer restrict it.

To restrict a query by collection you can either use the 'from' clause if using FlureeQL or via  SPARQL you could use ‘a’ or ‘rdf:type’ as the predicate.
