### ISSUE TITLE
Query performance using "orderBy"

### ISSUE THREAD

**Issue by atlewee** [fluree/db#204]
First of all, this is an amazing product! 
But during my testing I got some performance issues:
Running below query without "orderBy" takes 1.2ms 
with ordering it is always above 5000ms

Is this the performance I should expect from fluree queries, or am I doing something wrong?

![image](https://user-images.githubusercontent.com/11732817/191258105-8595be2c-0ff0-44f3-8fb1-f9d7a2ba3633.png)

**Info:**
I have a custom collection called "tag". (not the built in _tag collection)
The "tag/name" predicate has index: true.  ( max number of characters in the dataset is 26 )
There is about 200.000 subjects in my tag collection
I have no other collections in the ledger/database
Fluree is running on localhost (docker)

**Comment by bplatz** [comment]
Hi. This issue has been addressed in v3 of the product.
