### ISSUE TITLE
@type datatype coercion for xsd types

### ISSUE THREAD

**Issue by dpetran** [fluree/db#224]
Fill out the remaining table of what can/should be coerced - just xsd datatypes.

**Comment by cap10morgan** [comment]
Do we have that coercion table fleshed out? I'd be happy to work on this if so.

**Comment by bplatz** [comment]
@cap10morgan 
Yes! https://github.com/fluree/db/blob/main/src/fluree/db/datatype.cljc you'll see all of the data type constants, and below the coercion function which only thus far has string, anyURI, and boolean but needs the rest (which currently it just allows to pass through)
