### ISSUE TITLE
two-tuple identifiers in place of @id

### ISSUE THREAD

**Issue by dpetran** [fluree/db#225]

**Comment by bplatz** [comment]
I don't see this as being a necessary feature in the short-term and is non-standard for the RDF world. Its implementation would not be clear, as we aim to support uniqueness on properties but *within* a class. Meaning the same property, even though is unique within a class, could be duplicated across classes.

If important, we could devise a way of knowing if something was globally unique, or support a more lenient version of this where you can use two-tuple identifiers but it will always grab `(first ...)` from the results, and in the case there are multiple matches we cannot guarantee which it will resolve to.

**Comment by bplatz** [comment]
As per comment above, I don't see this as an alpha-2 task and I'm not sure it is even a requirement. Probably worth a discussion if it seems like this is needed to others. The concept goes against the purpose of JSON-LD, so if there is a requirement here we'd have to reconcile how to handle these differences.

**Comment by bplatz** [comment]
I suggest closing this ticket. This can be accommodated mostly via standard query syntax (e.g. `[?x :some/property "some value"]`)

This capability is not part of the SPARQL or related specifications I think for this reason. I think we should consider adding a uniqueness constraint into a SHACL shape (SHACL itself doesn't support this, so it would be a custom Fluree property inside a SHACL definition).

This idea is covered in #222 and I think that ticket should stay open.

**Comment by bplatz** [comment]
As per above comment, closing.
