### ISSUE TITLE
query context used for query expansion

### ISSUE THREAD

**Issue by dpetran** [fluree/db#227]

**Comment by bplatz** [comment]
@dpetran Do you recall what this was for? I think we do this already. Can't recall if there was a bug or I misunderstand.

**Comment by dpetran** [comment]
This is not working consistently in js, this issue is to remind us to try out different contexts and make sure that they are being handled consistently.

**Comment by bplatz** [comment]
This has been resolve in #262. If there is a specific use case broken here please reopen.
