### ISSUE TITLE
allow identical values within @list

### ISSUE THREAD

**Issue by dpetran** [fluree/db#235]

**Comment by bplatz** [comment]
In order for this to work, Flake sorting for indexes must start to include the `:i` key's value of the `m` map. Else sorting will see two identical object values of the same datatype as the same - and it won't insert the duplicates. (`:i` holds the index position for list values.)

This needs to get thought through a bit as sorted sets is the most impactful performance bottleneck for basically everything in Fluree... so extending the sorting logic will extend the sorting time and it needs to hopefully be done in a way where it only will affect sorting time if :i is present

**Comment by dpetran** [comment]
Blocked by Blocked by #461, we'll need to be able to gauge what sort of impact changes to list indexing have on overall performance.
