### ISSUE TITLE
update SPARQL parser

### ISSUE THREAD

**Issue by dpetran** [fluree/db#236]

**Comment by bplatz** [comment]
Please ask Ben & Brian questions!

**Comment by bplatz** [comment]
@mpoffald With your PR, not sure if this can be marked complete or if there is some more to do.

**Comment by mpoffald** [comment]
@bplatz Not quite done. At a minimum, I'd like to finish looking at the functions to make sure those are working and add tests for them, that was not included in my first PR.

After that, doneness depends on whether the goal here is to implement the whole SPARQL spec, or just ensure that existing code is working properly. What are the acceptance criteria?

**Comment by mpoffald** [comment]
Upon further inspection, there's nothing else that needs to be done right this moment. We'll probably come back and do a second pass later anyway, so I'm closing this for now and we can open new issues for anything that needs to be revisited.
