### ISSUE TITLE
support filter in where statements

### ISSUE THREAD

**Issue by bplatz** [fluree/db#249]

**Comment by mpoffald** [comment]
Initial support for filters was added in https://github.com/fluree/db/pull/270.

I've broken out follow-up issues for the remaining filter work that was identified:
- fix simple-subject-crawl: https://github.com/fluree/db/issues/269. (Fixing this may also fix filtering for simple-subject-crawl queries, and if not, we'll need to address that too.)
- nesting functions inside of filters: https://github.com/fluree/db/issues/272

Closing this in favor of the above followups.

**Comment by aaj3f** [comment]
Adding one more filter scenario in #360, in-line clause filters, where the filter function replaces an object value in a `where` clause, e.g. 
```json
{ "select": { "?s": ["*"] }, "where": [ ["?s", "ex:favNum", "#(> ?favNum 10)"] ] }
```
