### ISSUE TITLE
Create HTTP API server for basic ledger / db ops

### ISSUE THREAD

**Issue by cap10morgan** [fluree/db#267]
- create ledgers
- query ledgers
- transact against ledgers

**Comment by dpetran** [comment]
What sort of api are you looking at here? One thought is that we don't include the ledger name in the path, but rather require a ledger address as a param. This would simplify the solution for #268 .

**Comment by bplatz** [comment]
Is this a stateless query server API, or a dedicated ledger server? I think there is a strong dependency between the two, as the former will need to receive updates from the latter as to the state of the world, or it will need to self-contain one or more 'name services' to constantly figure out what the latest version of a ledger is.

If a file system that will be harder to do as the ledger server is really what is needed there. If this is monitoring for IPNS updates that is easier (but will have to connect to an IPFS servers).

I guess I'm wondering if the ledger server is the chicken and the egg here... and then for certain protocols (like IPFS) one could run without a ledger server.

**Comment by cap10morgan** [comment]
Right now it's a simple wrapper / translation of the json-ld api namespace to HTTP. It's intended to be plugged into various deployments of other components (ledger server, consensus, etc.) to provide an HTTP API to interact with ledgers. It doesn't yet try to do anything fancy like subscribe to updates. It is an experiment in isolating _just_ the HTTP API translation into a separate component that doesn't have to care what other components are providing what features behind it (e.g. consensus on transaction ordering, data caching for queries, etc.). And an experiment in trying out things like donut-system, reitit, request validation, auto-generation of OpenAPI docs, etc.

It's still pretty simple because it's been blocked by the inability to load existing data, which is pretty fundamental for a stateless protocol like HTTP. That's mostly unblocked now except for #268.

**Comment by cap10morgan** [comment]
Closed by https://github.com/fluree/http-api-server (& #290 but we can close this while those changes are discussed)
