### ISSUE TITLE
cannot use a new ledger from a stateless context

### ISSUE THREAD

**Issue by cap10morgan** [fluree/db#268]
When creating a new ledger via e.g. an HTTP API, you can't do anything with it because any subsequent `fdb/load` calls don't have anything to load from e.g. the file system. Should we create a stub file that the system can load to allow transacting against the new ledger?

**Comment by dpetran** [comment]
So this is a ledger with no commits? I wonder how other conns handle that case.

**Comment by cap10morgan** [comment]
> So this is a ledger with no commits? I wonder how other conns handle that case.

correct

**Comment by bplatz** [comment]
Should it exist without any commits? I prefer the idea that it doesn't... meaning a ledger only exists 'client-side' in memory until the first commit.

However we do need a catalog on disk of the ledgers. DB files should all be content-addressed, so I don't like the idea of keeping these in sub-directories based on a ledger alias (which itself could change)... however I think it is OK to keep the commit files (which reference the db files) in sub-directories as they are in theory unique.

**Comment by cap10morgan** [comment]
This is talking about a slightly higher-level issue is more about DX than implementation. If we're going to have the concepts of `create` and `load` in our API, then you should be able to `load` after `create` even if you don't do anything else in between (because in plenty of contexts, e.g. HTTP, you can't really).

Even if under the hood that gets implemented as basically-just-another-create when you "load" an empty ledger, that would be fine. Right now you get an exception.

Alternatively we could require an initial transaction w/ the create payload for stateless scenarios like HTTP.

**Comment by bplatz** [comment]
So we should probably rethink `create` and maybe favor something like `initialize` or other verb.

**Comment by dpetran** [comment]
I think we should have a request that looks like this:

`{tx: [...], ledger: "<ledger-address>", action: "create"}`

The server should then load the ledger address, if it can find it, or if that throws and the action is "create", create the ledger and then transact the tx. If action is not "create" we would return an error response.

**Comment by bplatz** [comment]
I like this solution as an option... maybe others still to come in, but with this one the DX would be:
a) (def myledger (fluree/initialize my-conn "my/db-name" {opts}) )
b) (def mydb (fluree/stage myledger [...])
c) (fluree/commit mydb)

In step 'c', we'd know already this is a new ledger and when committing to a remote server we can automatically add the `action` key (I prefer `new` vs `create`, but debatable).

I like the idea that if the ledger already exists, we'd throw at step 'c'. If not, and the user can create new ledgers (based on the server's config), it will succeed.

**Comment by dpetran** [comment]
@bplatz Are you talking about building an http `conn` method? I was thinking that what Wes is working on here would be a wrapper around, say, a file conn or an ipfs conn.

**Comment by cap10morgan** [comment]
Seems like there's a consensus around supplying an initial transaction when creating a new ledger in a stateless context (so that there is something reified there to refer to in future requests). That seems like enough to proceed and I can close this.
