### ISSUE TITLE
Queries with extraneous `where` clauses hang.

### ISSUE THREAD

**Issue by zonotope** [fluree/db#276]
Queries that have where clauses referencing variables not referenced in the select clause causes the query engine to hang, neither returning a result set and error message. For example, the following query never completes:

```clojure
user> @(fluree/query db '{:context  {:ex "http://example.org/ns/"}
                          :select   [?name ?email]
                          :where    [[?s :schema/name ?name]
                                     [?s :schema/email ?email]
                                     [?s :ex/favNums ?favNums]]})
```

We should ignore the unnecessary where clauses to report results as if they were not there.

**Comment by mpoffald** [comment]
Closed by #304
