### ISSUE TITLE
deprecate fluree "from", support implicit "where", use "from" for graphs

### ISSUE THREAD

**Issue by dpetran** [fluree/db#282]

**Comment by mpoffald** [comment]
Closing in favor of #280

**Comment by bplatz** [comment]
This is not related to #280. This is to support a select-only statement to have the same convenience, when needed, that our traditional `from` offered.


e.g. you used to do this:
```
{:select [:*]
 :from :ex/brian}
```
To offer the same convenience while allowing us to use `FROM` from the SPARQL-intended purpose, we would allow:
```
{:select {:ex/brian [:*]}}
```
```

**Comment by mpoffald** [comment]
@bplatz Making sure I understand correctly:

- #280 proposes using `from` only for ledger addresses
- this issue would be to have select-only statements, with neither a `from` nor a `where`

If so, we should update this issue to not include the language "use 'from' for graphs", as it involves not using `from` at all.

**Comment by bplatz** [comment]
@mpoffald I see this was opened just 5 days ago, so perhaps I'm not sure what is meant here. What I referenced above is the solution we discussed in the main planning meeting when discussing eliminating the `:from` query keyword.

**Comment by mpoffald** [comment]
@bplatz iirc it shows as opened 5 days ago because it was a draft issue until then. It very likely is the same issue that originated in the planning meeting.
