### ISSUE TITLE
Spike on feasibility of fractal API concept

### ISSUE THREAD

**Issue by cap10morgan** [fluree/db#289]
I want to see if we build an API that more or less works / looks the same regardless of which components you're talking to and/or are layered behind the component(s) you're talking to. For example, you should be able to use more or less the same API whether you're directly interacting with JSON-LD data on disk vs. talking to a whole cluster of query cache nodes, transaction servers, and/or consensus layers.

The first thing to investigate here is the feasibility of returning just immutable Clojure data / EDN from the json-ld.api fns (instead of the stateful Java objects we currently return) and then spike out a basic transaction server and a basic query cache server and then try integrating those behind the HTTP API server.

**Comment by bplatz** [comment]
Thinking about query and transact specifically, these can easily be multiple MB payload. If I understand this correctly, translating from a CLJ object to EDN, to then read into a CLJ object, to then output as JSON would add significant delays.

**Comment by cap10morgan** [comment]
Going to call this done now. I feel confident enough in it to propose a small usage of it in an upcoming PR. We can discuss it in that context when/if that happens.
