### ISSUE TITLE
New policy enforcement not getting applied during query execution

### ISSUE THREAD

**Issue by bplatz** [fluree/db#300]
The new policy enforcement code ends up validating flakes via `allow-flake?` which is leveraged by our extensively used `index-range` internal API. However, the new query code works around `index-range`, which does not have lazy output, in order to achieve laziness.

This workaround code should also be calling the policy enforcement code using `allow-flake?` similar to how index-range currently does.

The reason the policy enforcement is working in our tests is that they all use subject-crawls in the `:select`. The subject crawl code uses `index-range` under the hood. If a subject crawl was not used, you would not see filtered results. This needs to get addressed.

**Comment by bplatz** [comment]
The new policy enforcement code ends up validating flakes via `allow-flake?` which is leveraged by our extensively used `index-range` internal API. However, the new query code works around `index-range`, which does not have lazy output, in order to achieve laziness.

This workaround code should also be calling the policy enforcement code using `allow-flake?` similar to how `index-range` currently does.

The reason the policy enforcement is working in our tests is that they all use subject-crawls in the `select`. The subject crawl code uses `index-range` under the hood. If a subject crawl was not used, you would not see filtered results. This needs to get addressed.

**Comment by mpoffald** [comment]
For an example that will fail to enforce the policy until this work is done: any of the existing policy enforcement tests will fail if the `select` statement is not a graph crawl
