### ISSUE TITLE
Wrong reference ids when transacting

### ISSUE THREAD

**Issue by kellyprogramsthings** [fluree/db#307]
Transaction:
```
{
  "@context": "http://schema.org/",
  "@type": "MusicEvent",
  "location": {
    "@type": "Place",
    "address": {
      "addressLocality": "Raleigh",
      "addressRegion": "NC",
      "postalCode": "27609",
      "streetAddress": "2820 Industrial Drive",
      "@type": "PostalAddress",
      "addressCountry": {
        "@type": "Country",
        "name": "US"
      }
    }
  }
}
```

results in the MusicEvent location pointer containing the id for country.

Jake checked the data written to disk after transacting and shared this image with me:
![CleanShot 2022-12-28 at 11 37 17@2x](https://user-images.githubusercontent.com/36338287/209859498-45c974f7-5063-47d3-8b94-d61c4e65203d.png)

**Comment by cap10morgan** [comment]
Unable to reproduce with latest db main HEAD (9e9718b11e954c47621ea2c4651105f6d0765535)
