### ISSUE TITLE
Implement BIND for FlureeQL

### ISSUE THREAD

**Issue by zonotope** [fluree/db#314]
Add BIND clauses like those specified in the [SPARQL Spec](https://www.w3.org/TR/sparql11-query/#bind) to FlureeQL

~Blocked by #304~

**Comment by cap10morgan** [comment]
Implementation should roughly follow the [relevant existing FlureeQL docs](https://developers.flur.ee/docs/overview/query/analytical_query/#two-tuple-variable-binding) unless there are compelling reasons to deviate.
