### ISSUE TITLE
Build scaffolding of a JSON-LD nexus-backend that integrates with http-api-gateway

### ISSUE THREAD

**Issue by cap10morgan** [fluree/db#315]
Nexus has some Nexus-specific backend server requirements (e.g. customer log persistence and fuel tracking) that we want to handle in its HTTP API layer. We should utilize the existing http-api-gateway and build a the scaffolding of a server we can run on the JVM in a Docker container that provides the JSON-LD HTTP API but also gives a place to do the Nexus-specific tasks we need.

**Comment by bplatz** [comment]
This ticket is really a Nexus ticket FWIW, not part of Fluree Core and discussion should happen in the Nexus ticketing. I think there are some sub-tickets (or at least specific requirements around capturing fuel, etc.) that I'd like to add but not in the public domain.

**Comment by cap10morgan** [comment]
> This ticket is really a Nexus ticket FWIW, not part of Fluree Core and discussion should happen in the Nexus ticketing. I think there are some sub-tickets (or at least specific requirements around capturing fuel, etc.) that I'd like to add but not in the public domain.

Yeah, I had that same thought. It's just a little easier w/ our current project management tooling to have them in this repo. I can move it, though.
