### ISSUE TITLE
Support SHACL `class` contraint

### ISSUE THREAD

**Issue by dpetran** [fluree/db#316]
https://www.w3.org/TR/shacl/#core-components-value-type

A transaction that violates a value type constraint should return a validation error.

**Comment by bplatz** [comment]
@dpetran I believe this should already work - is there a specific value type this ticket should be covering.

**Comment by dpetran** [comment]
Per https://github.com/fluree/db/pull/501, we're not properly supporting "sh:class" constraints currently. The test introduced in PR 501 should fail (and be updated) once "sh:class" is enforced.

**Comment by aaj3f** [comment]
## Description

Support for `sh:class` constraints specifically, as described in https://www.w3.org/TR/shacl/#core-components-value-type

This allows restriction of a property to only take, as its object value, nodes of 1 or more specific classes, specified on `sh:class`

**Comment by cap10morgan** [comment]
@dpetran What would the passing test look like once this is done?

**Comment by dpetran** [comment]
All we need to do is add the class to the country assertion, so if you add the Country class to the `country` property the test should pass:
https://github.com/fluree/db/blob/1ffcf96ce103d46c192da9ed8031134cda11c31f/test/fluree/db/shacl/shacl_basic_test.clj#L951

**Comment by cap10morgan** [comment]
I updated the title to reflect that this card is only about supporting `class` now.
