### ISSUE TITLE
Support SHACL shape-based contraints

### ISSUE THREAD

**Issue by dpetran** [fluree/db#322]
https://www.w3.org/TR/shacl/#core-components-shape

Transactions that violate shape-based constraints should return an error.

**Comment by dpetran** [comment]
Possibly related: db #339

**Comment by aaj3f** [comment]
## Description

This provides support for NodeShape constraints on object nodes of a particular property, which is separate from providing NodeShape constraints on a class, entities of which may exist as objects of a particular property. The distinction, then, is that a property can define a NodeShape for its object references without having to separately apply a NodeShape on those entities, separate from the property which refers to them
