### ISSUE TITLE
Support SHACL in contraint

### ISSUE THREAD

**Issue by dpetran** [fluree/db#323]
https://www.w3.org/TR/shacl/#core-components-others

Transactions that violate the "other" constraints should return an error.

UPDATE: The other "other" constraints are either already implemented or captured by other tickets. Edited title to reflect the fact that this is just about supporting `in` now.

**Comment by mpoffald** [comment]
It looks like `sh:closed` and `sh:ignoredProperties` are already implemented: https://github.com/fluree/db/blob/main/test/fluree/db/shacl/shacl_basic_test.clj#L144. Probably not a bad idea to see if we should have more test coverage, but the implementations seem to be there.
