### ISSUE TITLE
Support SHACL target targetNode

### ISSUE THREAD

**Issue by dpetran** [fluree/db#325]
https://www.w3.org/TR/shacl/#targetNode

This will target a shape at the node with the given @id.

**Comment by aaj3f** [comment]
## Description

This provides support for SHACL `sh:targetNode`, which allows a shape to be applied not just to abstracted instances of a particular class, but allows for individual nodes/entities to be targeted directly

**Comment by dpetran** [comment]
Added in https://github.com/fluree/db/pull/755
