### ISSUE TITLE
Support for inline filter functions in object position of where clause

### ISSUE THREAD

**Issue by aaj3f** [fluree/db#360]
### Description

In addition to filtering binding values in queries using a filter map, support is required for in-line filter functions, where the filter function replaces the object value position in a where clause, e.g.

```json
{ "select": { "?s": ["*"] }, "where": [ ["?s", "ex:favNum", "#(> ?favNum 10)"] ] }
```

These are used in Nexus and are common across client use cases, in part because they have historically tended to be more performant, only associating values to the `?favNum` binding that meet the filter criteria, instead of pulling ALL values into memory and then performing the filter function across all of them. 

### Acceptance Criteria

- A filter function can be provided directly within a where clause triple, associating object values to the binding only when they meet the filter criteria
- Support for subject or predicate filter functions is NOT required

### Implementation Details

- Legacy where clause parsing code related to the keyword, `:object-fn`, might demonstrate how this was implemented in v2

**Comment by zonotope** [comment]
> These are used in Nexus and are common across client use cases, in part because they have historically tended to be more performant, only associating values to the `?favNum` binding that meet the filter criteria, instead of pulling ALL values into memory and then performing the filter function across all of them.

This is no longer the case. Filters are now applied to the relevant flakes as they are loaded, so flakes that don't meet the filtering criteria don't make it into the query processor at all, even if the filter is specified in a map. 

I think implementing this would also require a bit of special-case code to bind the new filtered variable to the right values, but it's definitely doable. The benefits would be purely syntactic however, as the following queries would have no difference in performance:

```clojure
'{:select {?s: [:*}}
  :where  [[?s :ex/favNum ?favNum]
           {:filter (> ?favNum 10)})}

'{:select {?s: [:*]}
  :where  [[?s :ex/favNum (> ?favNum 10)]]}

**Comment by aaj3f** [comment]
That's excellent, @zonotope -- I'll deprioritize this, in that case!

**Comment by bplatz** [comment]
We think we can close this, but lets discuss to confirm @aaj3f

**Comment by dpetran** [comment]
Closing because this syntax is redundant.
