### ISSUE TITLE
Errors serializing index nodes

### ISSUE THREAD

**Issue by zonotope** [fluree/db#410]
Some index nodes are not successfully serialized during the indexing process and fail with silent errors leading to subsequent errors while executing later queries:

```
08:35:01.337 [async-dispatch-3] ERROR fluree.db.serde.avro - Error serializing index leaf data: "<snipped>"
org.apache.avro.UnresolvedUnionException: Not in union ["long","int","string","boolean","float","double",{"type":"record","name":"BigInteger","fields":[{"name":"val","type":"string"}]},{"type":"record","name":"BigDecimal","fields":[{"name":"val","type":"string"}]},{"type":"record","name":"URI","fields":[{"name":"val","type":"string"}]},{"type":"record","name":"UUID","fields":[{"name":"val","type":"string"}]}]: null
	at abracad.avro.ClojureDatumWriter.resolveUnion(ClojureDatumWriter.java:83)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:143)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
	at abracad.avro.ClojureDatumWriter.write(ClojureDatumWriter.java:51)
```

**Comment by bplatz** [comment]
When I've seen this before it has been a transaction error where often you'll see a `nil` for `.-o` of the Flake.

Another possibility is with our new data types we need to extend the Avro type set, but I'd guess that is less likely. Maybe a clue if possibly the issue by looking at the `.-dt` of the Flakes for that index node that is erroring to see if anything sticks out.

**Comment by zonotope** [comment]
> When I've seen this before it has been a transaction error where often you'll see a `nil` for `.-o` of the Flake.
> 
> Another possibility is with our new data types we need to extend the Avro type set, but I'd guess that is less likely. Maybe a clue if possibly the issue by looking at the `.-dt` of the Flakes for that index node that is erroring to see if anything sticks out.

It's definitely a null `.-o`, but I didn't notice any errors in the tx logs, and the server returned a successful response.

For reference, I discovered this issue while trying to track down https://github.com/fluree/http-api-gateway/issues/33. The schema.org vocab is pretty big, and it's being transacted all at once, so there could very well be either a resource contention or data format issue that's causing an error in the transact, but that error looks to be silent at this point.

**Comment by bplatz** [comment]
My guess is the vocab uses something we haven't seen/tested/supported before. e.g. Schema.org uses it own custom data types which we don't fully support yet... I had previously done some custom coding to just coerce schema.org data types specifically into their equivalent XSD data types. Maybe not that, but something *like* that is probably the cause.
