### ISSUE TITLE
Browser-based commit, stage (and possibly other things) have broken

### ISSUE THREAD

**Issue by bplatz** [fluree/db#412]
From Jonathan: 

It’s been a while since I updated the fluree-browser-sdk deps in the Playground app, and committing and staging are broken when trying to update to the latest version (built from 8775f13efae89735defbc5bb9eb8378c19075b43).
Current implementation is at https://github.com/fluree/jld-browser-sandbox/blob/main/src/hooks/fluree.js if anybody has a moment to take a peek and let me know if I’m doing something wrong.
The working, deployed version of the playground is using fluree-browser-sdk built from fluree/db commit 9c303019fefe2d210b0867a0d3c815388ae85f56

**Comment by cap10morgan** [comment]
Should the acceptance criteria for this include some basic API smoke tests that run in the browser?

**Comment by dpetran** [comment]
I thought we already had them, so maybe there's a problem with the ci? If we don't we definitely should.

**Comment by mpoffald** [comment]
@jdorety We changed the signatures of the stage and commit fns a while back (in https://github.com/fluree/db/pull/343), I suspect this caused (or at least contributed) to the breakage:
- staging now operates on dbs only (not ledgers)
- committing requires a ledger _and_ a db as inputs

**Comment by cap10morgan** [comment]
> @jdorety We changed the signatures of the stage and commit fns a while back (in #343), I suspect this caused (or at least contributed) to the breakage:
> 
> * staging now operates on dbs only (not ledgers)
> * committing requires a ledger _and_ a db as inputs

I _think_ I updated those at the time the change was made, and looking over the fn signatures, it looks like I did (sans some outdated arg naming in `stage`; should just be `db` now). But the issue could still be related to that, and it's odd that the tests / CI don't seem to break.

**Comment by mpoffald** [comment]
I'm confused, what was the indication that the build itself is broken (or that CI wasn't working)?

I just made updates to `stage` and `commit` in jld-browser-sandbox to accommodate the signature changes and pushed it up here (branched off the `update-dependency` branch): https://github.com/fluree/jld-browser-sandbox/commit/fb8c3cc3d77da9a74b5bf5b5e47c95cf69ab7a3d

On this commit I don't see errors when staging or committing.

**Comment by cap10morgan** [comment]
OK, there's a few things to unpack here:

1. I'm not sure what fluree/jld-browser-sandbox is? Is it a wrapper for the db browser lib?
2. This bug is against the db lib. Was there anything broken in db? Seems like no?
3. If nothing was broken in db, then that's why the tests and CI were passing. So that's all fine.
4. If both are correct, then I think we can close this. But I'd be curious what made it seem like these fns weren't working in the browser and if we can address the source of that (apparent) breakage?

**Comment by mpoffald** [comment]
> I'm not sure how best to communicate those sorts of changes at this stage (where they could be frequent)

Fwiw I'm pretty sure this particular breaking change predates the two methods we now have for communicating this: the `requires doc updates` label, and the [wiki](https://github.com/fluree/flhubee/wiki/HTTP-API). But maybe we need something else too, idk.

**Comment by jdorety** [comment]
Thanks for the changes you made @mpoffald, the app is working perfectly now. My blocker seems to have been the `stage` method in particular. The `db-or-ledger` parameter declaration led me to believe that I did not need to change the way I was calling it.
https://github.com/fluree/db/blob/8775f13efae89735defbc5bb9eb8378c19075b43/src/fluree/sdk/browser.cljs#L42-L43

**Comment by cap10morgan** [comment]
That’s ^^^ the outdated arg naming I was referring to. We should change that to just `db` in the sdk namespaces.

**Comment by mpoffald** [comment]
> We should change that to just db in the sdk namespaces.

I was thinking the same, I'll PR that real quick

**Comment by mpoffald** [comment]
Here's the PR for the arg rename: https://github.com/fluree/db/pull/416, but I'll go ahead and close this issue since everything's working ok.
