### ISSUE TITLE
Update how default context is stored in commit

### ISSUE THREAD

**Issue by bplatz** [fluree/db#449]
The default context as it is stored in a commit file is non-standard. It needs a full IRI identifier (namespaced), and needs to be a reference to a node, it is currently stored as a string.

This is quite high priority, as it will break commit file reads/loads once in place, so we want to have it before anyone is using v3.

The IRI should be:
`https://ns.flur.ee/ledger#defaultContext`

The `https://ns.flur.ee/ledger#` namespace context is stored in the `fluree/json-ld` library in the resources folder. We currently have an IRI defined in there for `https://ns.flur.ee/ledger#context` which was originally designed for this, but I think it should be explicit with `defaultContext` instead and be renamed as such. Note the currently definition does not describe it as a node with type `@id` as it was originally going to stored the stringified JSON as a value, but now it being a separate file it is actually a graph node, and so it should be updated to look as follows:
```
    "defaultContext": {
      "@id": "fluree:defaultContext",
      "@type": "@id"
    }
```

After modifying the source context .jsonld with this modification, you'll need to re-parse the updated .jsonld context file into .edn (an optimization Fluree uses) which can be done from the `user` namespace:
`(parse-context "https://ns.flur.ee/ledger/v1")`

This will auto-create the .edn version of the file in the same directory as the .jsonld source file. Automating this via a build process on the json-ld library is nice, but if it takes any additional time it should be a separate ticket in the icebox.

When referring to the `https://ns.flur.ee/ledger#defaultContext` in Fluree's commit file, the value should now be a node that looks like:

{
      "id": "fluree:context:<sha-hash-of-context-file>",
      "type": "flureeContext",
      "f:address": <current value of 'fluree-default-context'>
}

The above assumes `id` is aliased to @id, `type` is aliased to @type and `f` is aliased to  `https://ns.flur.ee/ledger#` as it currently is in the commit file.

All files we reference in the commit have this same pattern, the reason is that we can't always control a file name (e.g. via IPFS), so the file name gets stored in the `f:address` and is not a globally unique identifier for the file. The `id` should be globally unique, and is therefore the sha hash. In the future there could be a search for the `id` which is globally unique, and it may return many "addresses" to retrieve that ID, which might be stored in many different places.

**Comment by cap10morgan** [comment]
Another wrinkle in history query commit details: Because this new node has an `:f/address` flake, there are now two flakes in the commit flakes with `:f/address` predicates and the code currently just puts both of them in the commit details like this:

```
{:f/commit {:f/data {:f/address ["fluree:memory://b6dcf8968183239ecc7a664025f247de5b7859ac18cdeaace89aafc421eeddee"
                                     "fluree:memory://bcb581e731a7c0ceadcfbf432b4ee8cf046de377cc33f047bd05b6c47f9da94d"]}}}
```

I'm not seeing an obvious way to differentiate them at the moment, but I'll keep digging. Or if this is OK for now, let me know.

**Comment by cap10morgan** [comment]
OK I think I found a way to filter out the defaultContext flakes specifically so only the address of the actual user data appears in the commit details.
