### ISSUE TITLE
Flakes automatically created for internal use should not be visible to users

### ISSUE THREAD

**Issue by mpoffald** [fluree/db#483]
# Context
Relevant comment: https://github.com/fluree/db/issues/473#issuecomment-1548549172

We automatically create some flakes for internal use/optimization purposes, which do not have meaning for users, eg:

- this triple just maps a subject ids to an iri:
```clj
[:ex/bob :id "http://example.org/ns/bob"]
```

However triples like this are [currently returned by full-db s+p+o queries](https://github.com/fluree/db/blob/main/test/fluree/db/query/misc_queries_test.clj#L250)

We need to ensure they are never returned from any queries.

# Acceptance criteria

- Internal-only triples are not returned in any queries

**Comment by JaceRockman** [comment]
@bplatz Have we settled on how we want to handle these triples?

**Comment by bplatz** [comment]
Hi @JaceRockman - these are no longer produced with the SID refactor which is now on the main branch. Once you are running off the tip of main these will be gone.
