### ISSUE TITLE
Add support for language tags

### ISSUE THREAD

**Issue by mpoffald** [fluree/db#490]
See: https://www.w3.org/TR/2004/REC-rdf-concepts-20040210/#dfn-language-identifier, https://www.w3.org/TR/sparql11-query/#matchLangTags

**Comment by dpetran** [comment]
If language is present, we need to store in meta.

**Comment by bplatz** [comment]
Sample language transaction that should successfully store the language metadata:
```
{
  "@context": {"dcterms": "http://purl.org/dc/terms/"},
  "@id": "http://example.org/articles/8",
  "dcterms:title": [
    {
      "@value": "Das Kapital",
      "@language": "de"
    },
    {
      "@value": "Capital",
      "@language": "en"
    }
  ]
}
```

Then this query would return just the `de` language for title:
```
{"@context": {"dcterms": "http://purl.org/dc/terms/"},
 "select": ["?title"],
 "where": [["?x", "dcterms:title"  "?title"],
           {"filter": ["(= "de" (lang ?title))"]}]}
```

**Comment by aaj3f** [comment]
Prioritizing this as it's very common in JSON-LD datasets and goal for beta will be supporting JSON-LD documents users bring from existing JSON-LD data repos

**Comment by bplatz** [comment]
This issue is completed.
