### ISSUE TITLE
Certain multiple var binding queries not returning every matching result in v2

### ISSUE THREAD

**Issue by cap10morgan** [fluree/db#497]
These commented-out tests don't pass for some reason: https://github.com/fluree/ledger/pull/210/files/468020172ce3bf108d0e017cad72507cde4f5440#diff-0b3937ade9f280bcce4420c055700effa4690133a086c9c161ad29768783f638R202-R243

Seems like it could be a bug.

**Comment by JaceRockman** [comment]
@cap10morgan This Issue was created in the db repo, but the link points to a test in the ledger repo. Should this ticket be moved?

**Comment by cap10morgan** [comment]
@JaceRockman I don't think so. This is for v2 so db doesn't really have its own tests (or very many of them, at least). They're in the ledger repo instead.

**Comment by bplatz** [comment]
This is being closed in favor of v3 focus, but can be re-opened if a blocker for a production system.
