### ISSUE TITLE
[v2] use of `groupBy` with `vars` returns `null` results

### ISSUE THREAD

**Issue by aaj3f** [fluree/db#499]
## Description

Using `groupBy` with a `?binding` that is also a `?binding` in the `vars` map causes the query to return `null` results.

For example, the following query:
```json
{
    "selectDistinct": [
        "?studentName",
        "?studentId"
    ],
    "where": [
      ["?profile", "profile/name", "?studentName"],
      ["?profile", "profile/student_id", "?studentId"]
    ],
    "vars": {
        "?studentName": ["Gates Lowery", "Kate Giovacchini"]
    },
    "opts": {
      "groupBy": "?studentName"
    }
}

// =>

null
```

However, this same query would work were you to remove either the `vars` map or the `groupBy` opt.

**Comment by bplatz** [comment]
This appears to have been marked done in #514
