### ISSUE TITLE
Publish benchmarks

### ISSUE THREAD

**Issue by alexkreidler** [fluree/db#51]
I noticed [this file](https://github.com/fluree/db/blob/main/src/fluree/db/performance.clj) that seems to run some benchmarks.

It would be great if you could publish these; it would help users understand the scale and type of the workloads you run.

I understand the concern that internal benchmarks might not be representative or useful for comparison with other databases. In that case, I would encourage you to run some standardized benchmarks, like the common SPARQL ones: [BSBM](http://wifo5-03.informatik.uni-mannheim.de/bizer/berlinsparqlbenchmark/), [LUBM](http://swat.cse.lehigh.edu/projects/lubm/) and others from the [Linked Data Benchmark Council (LDBC)](http://ldbcouncil.org/).

This is a very cool project, and I think many people from the semantic web community or using existing graph databases would be interested in trying it out if it were more easily compared with other databases.

Thanks!

**Comment by bplatz** [comment]
Hi @alexkreidler thanks for the note. We will consider publishing these benchmarks and create an internal ticket to track to do so. Fluree does well more than a Semantic graph DB, i.e. SmartFunctions and embedded permissions (which would require the addition of an app server for a standard graph db), provable provenance, time travel... so we need to think through this a bit and where we want to draw comparisons.
