### ISSUE TITLE
Add ability to check `sh:datatype`, `sh:class`, `sh:nodeKind` constraints after flakes have been transacted

### ISSUE THREAD

**Issue by mpoffald** [fluree/db#533]
Our current implementations of `sh:class`, `sh:nodeKind`, and `sh:datatype` only fire when properties are first created, as an optimization that allows fast failure.  However, in some cases of shapes that use `sh:targetObjectsOf`,   `sh:node`, and likely `sh:targetSubjectsOf`, we need to be able to enforce these constraints on flakes that have already been transacted.

Here is a test for `sh:targetObjectsOf` that will fail until this is fixed (this is already added as a commented-out test in https://github.com/fluree/db/pull/532):
```clj
(let [conn   @(fluree/connect {:method :memory
                                       :defaults
                                       {:context test-utils/default-str-context}})
      ledger @(fluree/create conn "shacl-target-objects-of-test"
                                     {:defaultContext ["" {"ex" "http://example.com/ns/"}]})
      db1  @(fluree/stage (fluree/db ledger)
                                  [{"@id" "ex:friendShape"
                                    "type"           ["sh:NodeShape"]
                                    "sh:targetObjectsOf" {"@id" "ex:friend"}
                                    "sh:property"    [{"sh:path" {"@id" "ex:name"}
                                                       "sh:datatype" {"@id" "xsd:string"}}]}])
      db2  @(fluree/stage db1 [{"id"       "ex:Bob"
                                "ex:name" 123
                                "type"     "ex:User"}])
      db-forbidden-friend @(fluree/stage db2
                                      {"id"       "ex:Alice"
                                       "type"     "ex:User"
                                       "ex:friend" {"@id" "ex:Bob"}})]
    (is (util/exception? db-forbidden-friend))
    (is (str/includes? (ex-message db-forbidden-friend)  "data type")))
```

And an example for `sh:node`:
```clj
(let [conn   @(fluree/connect {:method :memory})
      ledger @(fluree/create conn "shape-constaints" {:defaultContext [test-utils/default-str-context
                                                                           {"ex" "[http://example.com/](http://example.com/)"}]})
      db0    (fluree/db ledger)

      db1    @(fluree/stage db0 [{"id" "ex:AddressShape"
                                  "type" "sh:NodeShape"
                                  "sh:property" [{"sh:path" {"id" "ex:postalCode"}
                                                  "sh:datatype" "xsd:string"
                                                  "sh:maxCount" 1}]}
                                 {"id" "ex:PersonShape"
                                  "type" "sh:NodeShape"
                                  "sh:targetClass" {"id" "ex:Person"}
                                  "sh:property" [{"sh:path" {"id" "ex:address"}
                                                  "sh:node" {"id" "ex:AddressShape"}
                                                  "sh:minCount" 1}]}])
      valid-person @(fluree/stage db1 [{"id" "ex:Bob"
                                        "type" "ex:Person"
                                        "ex:address" {"ex:postalCode" "12345"}}])
      invalid-person @(fluree/stage db1 [{"id" "ex:Reto"
                                          "type" "ex:Person"
                                          "ex:address" {"ex:postalCode" [12345]}}])]
    (is (= [{"id" "ex:Bob",
             "rdf:type" ["ex:Person"],
             "ex:address" {"id" "_:f211106232532997", "ex:postalCode" "12345"}}]
           @(fluree/query valid-person {"select" {"?s" ["*" {"ex:address" ["*"]}]}
                                        "where" [["?s" "id" "ex:Bob"]]})))
    (is (util/exception? invalid-person))
    (is (= "SHACL PropertyShape exception - sh:maxCount of 1 lower than actual count of 2."
           (ex-message invalid-person))))
```

In both examples, we erroneously allow the invalid transactions to proceed, because the `sh:datatype` constraints will not be enforced.

**Comment by dpetran** [comment]
`sh:hasValue` also isn't applied against a db-after, so it if it is part of a shape-based constraint or used with extended property paths or non-`sh:targetClass` targets then it isn't checked.

**Comment by dpetran** [comment]
These are some of the approaches that I'm considering for solving this:

1. Check only after processing
 My initial thought for this is to move checking these constraints from during flake creation to afterwards, when we invoke `shacl/validate-target`. We sacrifice the ability to short-circuit transaction processing in the case of a failed validation for the ability to _correctly_ enforce constraints. 

2. Check during processing *and* after processing
We can only enforce the constraints under a subset of the conditions in which they might appear, so we check what we can while processing but do the full, correct validation after processing as well. We do a little bit of extra work in the case of valid transaction but we can still short-circuit processing during an invalid transaction

3. Check constraints in some cases during processing and in other cases after processing
Similar to 2), but detect and track cases where we can enforce constraints during processing and only enforce the remainder afterwards. This is complex as we will need to introspect every shape we are using to figure out if it can be validated during transaction processing.

I'm leaning towards 1) but happy to hear other ideas.
