### ISSUE TITLE
Implement Subqueries

### ISSUE THREAD

**Issue by zonotope** [fluree/db#574]
We should add support for building up value bindings by processing subqueries expressed in the where clause. [SPARQL supports where-clause subqueries](https://www.w3.org/TR/sparql11-query/#subqueries), and our support should match that specification where possible.

This is blocked by https://github.com/fluree/db/issues/573 (or some other solution to convert iri string output from subqueries to a format that allows the outer query to process them correctly.

**Comment by bplatz** [comment]
This is now implemented: https://github.com/fluree/db/pull/794
