### ISSUE TITLE
targetNode doesn't work in Policy's

### ISSUE THREAD

**Issue by chrisdostert** [fluree/db#742]
When creating a Policy, `targetNode` does not grant any access. 

In sleuthing I found some comments in PRs (https://github.com/fluree/db/pull/350, and https://github.com/fluree/db/pull/295) indicating maybe It's not implemented yet? 

Separate but related, I noticed [the docs](https://next.developers.flur.ee/docs/learn/foundations/data-access-control/#targeting-nodes) seem to be wrong; they show `targetNode` as a string as opposed to a node reference (object with `@id`)

**Comment by chrisdostert** [comment]
Different but possibly related https://github.com/fluree/db/issues/327

**Comment by bplatz** [comment]
We've migrated policy to now use the more powerful and flexible Policy Queries - so this issue no longer applies. See: https://github.com/fluree/db/pull/790
